$schema: "/schemas/common/metaschema.json#"
title: "Outcome of a worker configuration evaluation"
type: object
properties:
  workerType:
    type: string
    minLength:    {$const: identifier-min-length}
    maxLength:    {$const: identifier-max-length}
    pattern:      {$const: identifier-pattern}
  providerData:
    type: object
  biddingStrategyData:
    type: object
  documentationData:
    type: object
  schemaData:
    type: object
required:
  - workerType
  - providerData
  - biddingStrategyData
  - documentationData
  - schemaData
additionalProperties: false
